print("=" * 30) 
print("\t 🛒 SuperMart Receipt 🛒") 
print("=" * 30) 
# Items and prices 
print("Item\t\tQty\tPrice") 
print("-" * 30) 
print("Apples\t\t2\t$1.50") 
print("Bananas\t\t1\t$0.75") 
print("Bread\t\t1\t$2.00") 
print("Milk\t\t1\t$1.80") 
print("-" * 30) 
print("Total:\t\t \t$6.05") 
print("=" * 30) 
print("\tThank You! Visit Again 😊") 
print("=" * 30)